import type { MediaSource } from "@/lib/types";

/**
 * Attribution registry — every external media/data dependency is tracked here
 * so sources are visible in config, not hidden in components.
 * Generated by scripts/fetch-data.mjs — do not edit by hand (CATALOG-driven).
 */
export const sources: MediaSource[] = [
  {
    label: "Qur'an audio — Islamic Network / QuranicAudio — Yasir Al-Dawsari (quran/yasser_ad-dussary, 48s S1, verified)",
    url: "https://download.quranicaudio.com/quran/yasser_ad-dussary/001.mp3",
    license: "Quran.com / QuranicAudio — public distribution",
  },
  {
    label: "Qur'an audio — mp3quran.net — Haitham Al-Dakhin (Hafs 'an 'Asim, 320kbps, no timings)",
    url: "https://server16.mp3quran.net/h_dukhain/Rewayat-Hafs-A-n-Assem/001.mp3",
    license: "mp3quran.net official hosted mushaf",
  },
  {
    label: "Qur'an audio — Islamic Network / QuranicAudio — Mishary Rashid Alafasy (quran/mishaari_raashid_al_3afaasee, 52s S1)",
    url: "https://download.quranicaudio.com/quran/mishaari_raashid_al_3afaasee/001.mp3",
    license: "Quran.com / QuranicAudio — public distribution",
  },
  {
    label: "Qur'an audio — Islamic Network / QuranicAudio — Abdul Basit Murattal (quran/abdul_basit_murattal, 47s S1, 97% ok)",
    url: "https://download.quranicaudio.com/quran/abdul_basit_murattal/001.mp3",
    license: "Quran.com / QuranicAudio — public distribution",
  },
  {
    label: "Qur'an audio — Islamic Network / QuranicAudio — Mahmoud Khalil Al-Husary (quran/mahmood_khaleel_al-husaree, 57s S1, fixes 428s drift of iza3a)",
    url: "https://download.quranicaudio.com/quran/mahmood_khaleel_al-husaree/001.mp3",
    license: "Quran.com / QuranicAudio — public distribution",
  },
  {
    label: "Qur'an audio — Islamic Network / QuranicAudio — Abdul Basit Mujawwad (quran/abdulbaset_mujawwad, 99s S1)",
    url: "https://download.quranicaudio.com/quran/abdulbaset_mujawwad/001.mp3",
    license: "Quran.com / QuranicAudio — public distribution",
  },
  {
    label: "Qur'an audio — Islamic Network / QuranicAudio — Abdur-Rahman as-Sudais (quran/abdurrahmaan_as-sudays, 38s S1)",
    url: "https://download.quranicaudio.com/quran/abdurrahmaan_as-sudays/001.mp3",
    license: "Quran.com / QuranicAudio — public distribution",
  },
  {
    label: "Qur'an audio — Islamic Network / QuranicAudio — Maher Al-Muaiqly (quran/maher_256, 36s S1, fixes 25.9s drift; fallback S5->year1440)",
    url: "https://download.quranicaudio.com/quran/maher_256/001.mp3",
    license: "Quran.com / QuranicAudio — public distribution",
  },
  {
    label: "Qur'an audio — Islamic Network / QuranicAudio — Saad Al-Ghamdi (quran/sa3d_al-ghaamidi/complete, 47s S1, perfect 0.27s avg)",
    url: "https://download.quranicaudio.com/quran/sa3d_al-ghaamidi/complete/001.mp3",
    license: "Quran.com / QuranicAudio — public distribution",
  },
  {
    label: "Qur'an audio — Islamic Network / QuranicAudio — Abu Bakr Al-Shatri (quran/abu_bakr_ash-shatri_tarawee7, 46s S1)",
    url: "https://download.quranicaudio.com/quran/abu_bakr_ash-shatri_tarawee7/001.mp3",
    license: "Quran.com / QuranicAudio — public distribution",
  },
  {
    label: "Surah metadata + Latin transliteration (6236 verses)",
    url: "https://api.alquran.cloud/v1/surah",
    license: "alquran.cloud (crowd-sourced; Qur'an text is public domain in most jurisdictions)",
  },
  {
    label: "Verse timings — 9 reciters (6236 verses each)",
    url: "https://quran.com",
    license: "Quran Foundation (QDC API) — verified high-precision verse timings",
  },
  {
    label: "Reciter portraits",
    url: "https://commons.wikimedia.org",
    license: "Wikimedia Commons / Public Domain / Fair Use",
  },
  {
    label: "Ambient audio + background videos (16 sounds)",
    url: "https://pixabay.com/sound-effects/",
    license: "Pixabay Content License — free for commercial use, no attribution required",
  },
];
