import type { MediaSource } from "@/lib/types";

/**
 * Attribution registry — every external media/data dependency is tracked here
 * so sources are visible in config, not hidden in components.
 * Generated by scripts/fetch-data.mjs — do not edit by hand (CATALOG-driven).
 */
export const sources: MediaSource[] = [
  {
    label: "Qur'an audio — Quran.com / QuranicAudio — Yasir Al-Dawsari (Full Surahs, 128kbps)",
    url: "https://download.quranicaudio.com/quran/yasser_ad-dussary//001.mp3",
    license: "Quran.com / QuranicAudio — public distribution",
  },
  {
    label: "Qur'an audio — mp3quran.net — Haitham Al-Dakhin (Hafs 'an 'Asim, 320kbps)",
    url: "https://server16.mp3quran.net/h_dukhain/Rewayat-Hafs-A-n-Assem/001.mp3",
    license: "mp3quran.net official hosted mushaf",
  },
  {
    label: "Qur'an audio — Quran.com / QuranicAudio — Mishary Rashid Alafasy (Murattal, verified timings)",
    url: "https://download.quranicaudio.com/qdc/mishari_al_afasy/murattal/1.mp3",
    license: "Quran.com / QuranicAudio — public distribution",
  },
  {
    label: "Qur'an audio — Quran.com / QuranicAudio — Abdul Basit Murattal (Murattal, verified timings)",
    url: "https://download.quranicaudio.com/qdc/abdul_baset/murattal/1.mp3",
    license: "Quran.com / QuranicAudio — public distribution",
  },
  {
    label: "Qur'an audio — Quran.com / QuranicAudio — Mahmoud Khalil Al-Husary (Murattal, verified timings)",
    url: "https://download.quranicaudio.com/qdc/khalil_al_husary/murattal/1.mp3",
    license: "Quran.com / QuranicAudio — public distribution",
  },
  {
    label: "Qur'an audio — Quran.com / QuranicAudio — Abdul Basit Mujawwad (Mujawwad, verified timings)",
    url: "https://download.quranicaudio.com/qdc/abdul_baset/mujawwad/1.mp3",
    license: "Quran.com / QuranicAudio — public distribution",
  },
  {
    label: "Qur'an audio — Quran.com / QuranicAudio — Abdur-Rahman as-Sudais (Murattal, verified timings)",
    url: "https://download.quranicaudio.com/qdc/abdurrahmaan_as_sudais/murattal/1.mp3",
    license: "Quran.com / QuranicAudio — public distribution",
  },
  {
    label: "Qur'an audio — Quran.com / QuranicAudio — Maher Al-Muaiqly (Year 1440, verified timings)",
    url: "https://download.quranicaudio.com/quran/maher_almu3aiqly/year1440//001.mp3",
    license: "Quran.com / QuranicAudio — public distribution",
  },
  {
    label: "Qur'an audio — Quran.com / QuranicAudio — Saad Al-Ghamdi (Complete, verified timings)",
    url: "https://download.quranicaudio.com/quran/sa3d_al-ghaamidi/complete//001.mp3",
    license: "Quran.com / QuranicAudio — public distribution",
  },
  {
    label: "Qur'an audio — Quran.com / QuranicAudio — Abu Bakr Al-Shatri (Murattal, verified timings)",
    url: "https://download.quranicaudio.com/qdc/abu_bakr_shatri/murattal/1.mp3",
    license: "Quran.com / QuranicAudio — public distribution",
  },
  {
    label: "Surah metadata + Latin transliteration (6236 verses)",
    url: "https://api.alquran.cloud/v1/surah",
    license: "alquran.cloud (crowd-sourced; Qur'an text is public domain in most jurisdictions)",
  },
  {
    label: "Verse timings — 9 reciters (6236 verses each)",
    url: "https://quran.com",
    license: "Quran Foundation (QDC API) — verified high-precision verse timings",
  },
  {
    label: "Reciter portraits",
    url: "https://commons.wikimedia.org",
    license: "Wikimedia Commons / Public Domain / Fair Use",
  },
  {
    label: "Ambient audio + background videos (16 sounds)",
    url: "https://pixabay.com/sound-effects/",
    license: "Pixabay Content License — free for commercial use, no attribution required",
  },
];
